export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  users: {
    me: '/users/me',
    achievements: '/users/me/achievements',
    updateMe: '/users/me',
    resetProgress: '/users/me/reset',
    changePassword: '/users/me/password',
  },
  levels: {
    list: '/levels',
    detail: (id: string) => `/levels/${id}`,
    questions: (id: string) => `/levels/${id}/questions`,
  },
  game: {
    sessions: '/game/sessions',
    session: (id: string) => `/game/sessions/${id}`,
    complete: (id: string) => `/game/sessions/${id}/complete`,
  },
  progress: {
    list: '/progress',
    level: (levelId: string) => `/progress/${levelId}`,
  },
  teacher: {
    analytics: '/teacher/analytics',
    summary: '/teacher/summary',
    groups: '/teacher/groups',
    groupStudents: (groupId: string) => `/teacher/groups/${groupId}/students`,
    assignStudent: (groupId: string, studentId: string) =>
      `/teacher/groups/${groupId}/students/${studentId}`,
    removeStudent: (groupId: string, studentId: string) =>
      `/teacher/groups/${groupId}/students/${studentId}`,
    unassignedStudents: '/teacher/students/unassigned',
    createStudent: '/teacher/students',
    studentProgress: (id: string) => `/teacher/students/${id}/progress`,
    resetStudentProgress: (id: string) => `/teacher/students/${id}/reset`,
    reportCsv: '/teacher/report/csv',
    questions: '/teacher/questions',
    myQuestions: '/teacher/questions/mine',
    questionStats: '/teacher/questions/stats',
    bankQuestions: '/teacher/questions/bank',
    updateQuestion: (id: string) => `/teacher/questions/${id}`,
  },
  analytics: {
    overview: '/analytics/overview',
  },
  admin: {
    stats: '/admin/stats',
    users: '/admin/users',
    user: (id: string) => `/admin/users/${id}`,
    teachers: '/admin/teachers',
    groups: '/admin/groups',
    group: (id: string) => `/admin/groups/${id}`,
    groupStats: '/admin/groups/stats',
    levels: '/admin/levels',
    level: (id: string) => `/admin/levels/${id}`,
    groupStudents: (id: string) => `/admin/groups/${id}/students`,
    groupStudent: (groupId: string, studentId: string) => `/admin/groups/${groupId}/students/${studentId}`,
    unassignedStudents: '/admin/students/unassigned',
    pendingQuestions: '/admin/questions/pending',
    approvedQuestions: '/admin/questions/approved',
    createQuestion: '/admin/questions',
    updateQuestion: (id: string) => `/admin/questions/${id}`,
    reviewQuestion: (id: string) => `/admin/questions/${id}/review`,
    toggleQuestion: (id: string) => `/admin/questions/${id}/toggle`,
    analytics: '/admin/analytics',
    seedReset: '/admin/seed/reset',
    seedDemo:  '/admin/seed/demo',
    seedE2e:   '/admin/seed/e2e',
  },
} as const
